# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

jobs:
  build   
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run simple java c"
        run:  |
          echo  "hi good morning "
          echo  "hi good morning guys "
